const LEVELS={0:'Kana Foundation',1:'Survival Japanese',2:'Everyday Conversation',3:'Natural Interaction',4:'Early Intermediate'};
const storeKey='kanaFirstJapaneseV3';
const defaultState={settings:{maxLevel:1,newLimit:15,dailyGoal:30,voice:'auto'},srs:{},daily:{},version:3};
let state=loadState(); let queue=[]; let qIndex=0; let revealed=false; let sessionMode='smart'; let sessionReviewed=0; let browseLevel='all';
function loadState(){try{const x=JSON.parse(localStorage.getItem(storeKey));return Object.assign(JSON.parse(JSON.stringify(defaultState)),x||{},{settings:Object.assign({},defaultState.settings,(x||{}).settings||{}),srs:(x||{}).srs||{},daily:(x||{}).daily||{}})}catch(e){return JSON.parse(JSON.stringify(defaultState))}}
function saveState(){localStorage.setItem(storeKey,JSON.stringify(state));updateStats()}
const $=id=>document.getElementById(id);
function todayKey(){return new Date().toISOString().slice(0,10)}
function dailyObj(){const k=todayKey();if(!state.daily[k])state.daily[k]={reviewed:0};return state.daily[k]}
function eligible(c){return c.level<=Number(state.settings.maxLevel)}
function rec(c){return state.srs[c.id]||null}
function dueCards(){const n=Date.now();return ALL.filter(c=>eligible(c)&&rec(c)&&rec(c).due<=n)}
function newCards(){return ALL.filter(c=>eligible(c)&&!rec(c))}
function balancedFresh(limit){const pool=newCards().filter(c=>!(c.kind==='Time Blitz'||(c.kind==='Listening'&&c.category==='Time')));const groups={};pool.forEach(c=>(groups[c.kind]||(groups[c.kind]=[])).push(c));Object.values(groups).forEach(shuffle);const order=['Kana Drill','Vocabulary','Production','Listening','Sentence','Fill in the Blank','Local Interaction','Grammar'];const out=[];let round=0;while(out.length<limit){let added=false;for(const k of order){const g=groups[k]||[];if(g[round]&&out.length<limit){out.push(g[round]);added=true}}if(!added)break;round++}return out}
function masteredCount(){return ALL.filter(c=>{const r=rec(c);return eligible(c)&&r&&r.interval>=21}).length}
function seenCount(){return ALL.filter(c=>eligible(c)&&rec(c)).length}
function updateStats(){$('dueStat').textContent=dueCards().length;$('masteredStat').textContent=masteredCount();$('seenStat').textContent=seenCount();const d=dailyObj();const goal=Number(state.settings.dailyGoal);$('goalBar').style.width=Math.min(100,(d.reviewed/goal)*100)+'%';$('goalText').textContent=`Today: ${d.reviewed} / ${goal} reviews`; $('headerLevel').textContent='L'+state.settings.maxLevel;}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeQueue(mode){sessionMode=mode;sessionReviewed=0;let pool=[];const levelCards=ALL.filter(eligible);if(mode==='smart'){const due=shuffle(dueCards());const fresh=balancedFresh(Number(state.settings.newLimit));pool=[...due,...fresh]; if(!pool.length)pool=shuffle(levelCards).slice(0,Math.max(10,Number(state.settings.newLimit)))}
else if(mode==='interactions')pool=levelCards.filter(c=>c.kind==='Local Interaction');
else if(mode==='listening')pool=levelCards.filter(c=>c.kind==='Listening');
else if(mode==='fill')pool=levelCards.filter(c=>c.kind==='Fill in the Blank');
else if(mode==='time')pool=levelCards.filter(c=>c.kind==='Time Blitz'||(c.kind==='Listening'&&c.category==='Time'));
else if(mode==='production')pool=levelCards.filter(c=>c.kind==='Production');
else pool=levelCards;
queue=shuffle([...pool]);qIndex=0;revealed=false;$('studyMode').value=mode;showView('study');renderCard();}
function card(){return queue[qIndex]}
function kanjiHtml(c){if(!c.kanji||!c.kanji.length)return '<strong>Kanji preview</strong><span class="muted">No kanji needed for this card.</span>';return '<strong>Optional kanji — not required</strong>'+c.kanji.map(x=>`<div><b>${x[0]}</b>（${x[1]}） — ${x[2]}</div>`).join('')}
function renderCard(){if(!queue.length){$('front').textContent='No cards match this mode at your current level.';$('back').classList.add('hidden');$('ratings').classList.add('hidden');return}const c=card();revealed=false;$('studyProgress').textContent=`${qIndex+1} / ${queue.length} · reviewed ${sessionReviewed}`;$('levelBadge').textContent=`L${c.level} · ${LEVELS[c.level]}`;$('kindBadge').textContent=c.kind;$('catBadge').textContent=c.category;$('front').textContent=c.front;$('front').classList.toggle('en',/^[A-Za-z🎧]/.test(c.front));$('answerKana').textContent=c.answer_kana;$('romaji').textContent=c.romaji;$('meaning').textContent=c.meaning;$('grammar').textContent=c.grammar||'Focus on understanding and producing the sentence naturally.';$('kanjiBlock').innerHTML=kanjiHtml(c);if(c.situation){$('situation').textContent='Situation: '+c.situation;$('situation').classList.remove('hidden')}else $('situation').classList.add('hidden');if(c.cue){$('cue').innerHTML='<b>Goal / context:</b> '+c.cue+(c.hint?`<div class="muted" style="margin-top:4px">${c.hint}</div>`:'');$('cue').classList.remove('hidden')}else $('cue').classList.add('hidden');$('back').classList.add('hidden');$('reveal').textContent='Reveal answer';$('ratings').classList.add('hidden');updateAudioButtons(c)}
function reveal(){if(!queue.length)return;revealed=!revealed;$('back').classList.toggle('hidden',!revealed);$('front').classList.toggle('hidden',revealed);$('situation').classList.toggle('hidden',revealed||!card().situation);$('cue').classList.toggle('hidden',revealed||!card().cue);$('reveal').textContent=revealed?'Show prompt':'Reveal answer';if(revealed&&sessionMode==='smart')$('ratings').classList.remove('hidden');else $('ratings').classList.add('hidden');updateAudioButtons(card())}
function next(d=1){if(!queue.length)return;speechSynthesis.cancel();qIndex=(qIndex+d+queue.length)%queue.length;renderCard()}
function rateCard(rating){const c=card();const now=Date.now();let r=state.srs[c.id]||{interval:0,ease:2.3,reps:0,lapses:0,due:now};let days=1;if(rating==='again'){days=10/(60*24);r.ease=Math.max(1.6,r.ease-.2);r.lapses=(r.lapses||0)+1}else if(rating==='hard'){days=r.reps===0?1:Math.max(1,r.interval*1.2);r.ease=Math.max(1.7,r.ease-.08)}else if(rating==='good'){days=r.reps===0?1:(r.reps===1?3:Math.max(2,r.interval*r.ease))}else{days=r.reps===0?4:Math.max(4,r.interval*r.ease*1.3);r.ease=Math.min(3.0,r.ease+.12)}r.interval=days;r.reps=(r.reps||0)+1;r.due=now+days*86400000;r.last=now;state.srs[c.id]=r;dailyObj().reviewed++;sessionReviewed++;saveState();queue.splice(qIndex,1);if(qIndex>=queue.length)qIndex=0;if(!queue.length){makeQueue('smart');return}renderCard()}
function updateAudioButtons(c){const promptText=c.audio_prompt||'';const answerText=c.audio_answer||c.answer_kana;const canPrompt=!!promptText; $('hearPrompt').disabled=!canPrompt&&!revealed;$('hearPrompt').textContent=revealed?'🔊 Hear answer':(canPrompt?'🔊 Hear prompt':'🔒 Reveal to hear');$('hearSlow').disabled=!canPrompt&&!revealed}
let jpVoices=[];function loadVoices(){const vs=speechSynthesis.getVoices();jpVoices=vs.filter(v=>/^ja[-_]/i.test(v.lang)||/Japanese/i.test(v.name));const sel=$('voiceSelect');const current=state.settings.voice;sel.innerHTML='<option value="auto">Auto — Japanese voice</option>'+jpVoices.map(v=>`<option value="${v.name.replace(/"/g,'&quot;')}">${v.name}</option>`).join('');sel.value=[...sel.options].some(o=>o.value===current)?current:'auto'}loadVoices();if('onvoiceschanged'in speechSynthesis)speechSynthesis.onvoiceschanged=loadVoices;
function speak(text,rate=.95){if(!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/___+/g,''));u.lang='ja-JP';u.rate=rate;u.pitch=1;let v=null;if(state.settings.voice!=='auto')v=jpVoices.find(x=>x.name===state.settings.voice);if(!v)v=jpVoices[0]||null;if(v)u.voice=v;speechSynthesis.speak(u)}
$('hearPrompt').onclick=()=>{const c=card();if(!c)return;const t=revealed?(c.audio_answer||c.answer_kana):(c.audio_prompt||'');if(t)speak(t,.95)};$('hearSlow').onclick=()=>{const c=card();if(!c)return;const t=revealed?(c.audio_answer||c.answer_kana):(c.audio_prompt||'');if(t)speak(t,.68)};
$('card').onclick=e=>{if(e.target.closest('button'))return;reveal()};$('reveal').onclick=reveal;$('prev').onclick=()=>next(-1);$('next').onclick=()=>next(1);document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rateCard(b.dataset.rate));
let sx=0;$('card').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('card').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>70&&sessionMode!=='smart')next(dx<0?1:-1)},{passive:true});
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='browse')renderBrowse();if(id==='settings')syncSettings()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>makeQueue(b.dataset.start));$('studyMode').onchange=e=>makeQueue(e.target.value);
function syncSettings(){$('maxLevel').value=state.settings.maxLevel;$('newLimit').value=state.settings.newLimit;$('dailyGoal').value=state.settings.dailyGoal;$('voiceSelect').value=state.settings.voice;$('deckMeta').textContent=`${ALL.length.toLocaleString()} total cards · Level 0: ${ALL.filter(c=>c.level===0).length} · L1: ${ALL.filter(c=>c.level===1).length} · L2: ${ALL.filter(c=>c.level===2).length} · L3: ${ALL.filter(c=>c.level===3).length} · L4: ${ALL.filter(c=>c.level===4).length}`}
$('maxLevel').onchange=e=>{state.settings.maxLevel=Number(e.target.value);saveState();updateStats();};$('newLimit').onchange=e=>{state.settings.newLimit=Number(e.target.value);saveState()};$('dailyGoal').onchange=e=>{state.settings.dailyGoal=Number(e.target.value);saveState();updateStats()};$('voiceSelect').onchange=e=>{state.settings.voice=e.target.value;saveState()};
function renderBrowse(){const kind=$('browseKind').value;const q=$('search').value.trim().toLowerCase();let arr=ALL.filter(c=>(browseLevel==='all'||c.level===Number(browseLevel))&&(kind==='All'||c.kind===kind)&&(!q||c.front.toLowerCase().includes(q)||c.answer_kana.toLowerCase().includes(q)||c.meaning.toLowerCase().includes(q)));$('browseCount').textContent=`${arr.length.toLocaleString()} cards`;$('browseList').innerHTML=arr.slice(0,120).map(c=>`<div class="listItem"><b>${c.answer_kana.replace(/\n/g,' · ')}</b><span>L${c.level} · ${c.kind} · ${c.category} · ${c.meaning}</span></div>`).join('')+(arr.length>120?'<div class="sub">Showing first 120 matches. Narrow the filters to see more.</div>':'')}
const kinds=['All',...new Set(ALL.map(c=>c.kind))];$('browseKind').innerHTML=kinds.map(k=>`<option>${k}</option>`).join('');$('browseKind').onchange=renderBrowse;$('search').oninput=renderBrowse;const bl=$('browseLevels');bl.innerHTML=['all',0,1,2,3,4].map(x=>`<button class="pill ${x==='all'?'on':''}" data-l="${x}">${x==='all'?'All levels':'L'+x}</button>`).join('');bl.querySelectorAll('button').forEach(b=>b.onclick=()=>{browseLevel=b.dataset.l;bl.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));renderBrowse()});
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='japanese-study-progress.json';a.click();URL.revokeObjectURL(a.href)};$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);saveState();syncSettings();alert('Progress imported.')}catch(err){alert('That file could not be imported.')}};r.readAsText(f)};$('resetProgress').onclick=()=>{if(confirm('Reset all study progress on this device?')){state.srs={};state.daily={};saveState();updateStats();}};
updateStats();syncSettings();renderBrowse();makeQueue('smart');showView('home');
